channel:
- access:
  - ZTF_PUB
  name: wise
  policy: []
  version: 0
mongo:
  prefix: AT2019qiz
  reset: true
name: timewise
task:
- config:
    compiler_opts: TiCompilerOptions
    directives:
    - channel: wise
      ingest:
        mux:
          combine:
          - state_t2:
            - unit: T2StackVisits
            - unit: T2FindQPEs
              config:
                t2_dependency:
                  - unit: T2StackVisits
            unit: T1HDBSCAN
            config:
              original_id_key: orig_id
              input_mongo_db_name: qpes_input
              plot: false
          unit: TiMongoMuxer
    iter_max: 1000
    shaper: TiDataPointShaper
    supplier:
      config:
        dpid: hash
        loader:
          config:
            timewise_config_file: /home/murff/software/qpes/timewise_config_AT2019.yml
            stock_id_column_name: orig_id
            skip_missing_files: false
          unit: TimewiseFileLoader
      unit: TimewiseAlertSupplier
  multiplier: 1
  title: t0
  template:
    live:
      - resolve_run_time_aliases
      - hash_t2_config
  unit: AlertConsumer
- config:
    log_profile: default
  multiplier: 1
  title: t2
  unit: T2Worker